---
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
queue:
  reply: RPCReply
  request: RPCRequest
exchange:
  direct: rpc-direct
routingKey:
  reply: RPCReply
  request: RPCRequest

